print("program means set of instruction that a computer can understand and execute.")
print("python is easier language to learn and use.")
print("print statement is used to display the output on the screen.")
print("python interpreter is act as a translator between the python code and the machine code.")
print(20+30)
print("20+30")
print("we use comments to explain the code and make it more readable.")
print("python is case sensitive language.")
print("# this is a comment")
print("if you forget the paranthesis in print statement then it will give syntax error.")
print("Hello")